### ISSUE TITLE
Doesn't work if the bot's main code is on discord.js v13

### ISSUE THREAD

**Issue by SCP1939** [helmasaur/horsengel-roulette#50]
I've tried to use this package for a command for my discord.js v13 discord bot, but it doesn't seem to work at all.
The only thing it does is prompt the user to use "!yes" to start and it stops there, doesn't matter if the other user says "!yes" or not.

**Comment by helmasaur** [comment]
Thank you very much for opening this issue! I saw that `discord.js` v13 just got released but I didn't get to see the differences yet. I will work on it and try to release an update in the next days!

**Comment by SCP1939** [comment]
Okay, thanks.

**Comment by helmasaur** [comment]
I'm giving you some updates on what's going on. I started modifications to make this package compatible with `discord.js` v13. Some other modifications are still needed and then, I will do some test to see if things work properly. I will try to publich the new version on npm tomorrow or the day after tomorrow (: !

**Comment by SCP1939** [comment]
Nice!

**Comment by helmasaur** [comment]
OK, so all has been fixed except one issue. I'm working on it to be able to publish everything as soon as possible. I'm on the last step. Thanks for your patience!

**Comment by SCP1939** [comment]
Thanks to you!

**Comment by helmasaur** [comment]
**Finally!**

After hours of tests, I could find the last issue left. The Horsengel roulette works on `discord.js` v13. It is late here so I will stop for now. I will check a last time tomorrow and indicate in the readme file what intents are required for this package. I will also upload it to npm tomorrow.

Thank you very much for your patience!

**Comment by helmasaur** [comment]
I have published the update on npm. If there is any bug, don't hesitate to open a new ticket on here. I will make a bug fix as fast as possible!
